# Generated by Django 5.0.3 on 2025-10-05 15:55

import apps.rooms.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=apps.rooms.models.generate_room_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("max_players", models.IntegerField(default=6)),
                (
                    "current_game",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_room",
                        to="games.game",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_rooms",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_ready", models.BooleanField(db_index=True, default=False)),
                ("score", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="users.player",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "db_table": "room_players",
                "ordering": ["-score", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["status", "-created_at"], name="rooms_status_77ceb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["code", "status"], name="rooms_code_ffc42e_idx"),
        ),
        migrations.AddIndex(
            model_name="roomplayer",
            index=models.Index(
                fields=["room", "player"], name="room_player_room_id_ddaef8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomplayer",
            index=models.Index(
                fields=["room", "-score"], name="room_player_room_id_ec867d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomplayer",
            unique_together={("room", "player")},
        ),
    ]
