# Generated by Django 5.0.3 on 2025-10-05 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=50)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Django session key for tracking",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("last_active", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "players",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="players_created_56bcdb_idx"
                    ),
                    models.Index(
                        fields=["username", "-created_at"],
                        name="players_usernam_2e1f98_idx",
                    ),
                ],
            },
        ),
    ]
