# Generated by Django 5.0.3 on 2025-10-05 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_question_index", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "games",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameScore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_score", models.IntegerField(db_index=True, default=0)),
                ("correct_answers", models.IntegerField(default=0)),
                ("wrong_answers", models.IntegerField(default=0)),
                ("rank", models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                "db_table": "game_scores",
                "ordering": ["-total_score", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(db_index=True)),
                ("text", models.TextField()),
                ("items", models.JSONField()),
                ("correct_answer", models.CharField(max_length=500)),
                ("hint", models.TextField(blank=True)),
                ("time_limit", models.IntegerField(default=30)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answer_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(db_index=True, default=False)),
                ("used_hint", models.BooleanField(db_index=True, default=False)),
                ("time_taken", models.IntegerField()),
                ("points_earned", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="users.player",
                    ),
                ),
            ],
            options={
                "db_table": "answers",
                "ordering": ["-created_at"],
            },
        ),
    ]
