# Generated by Django 5.0.3 on 2025-10-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        ("rooms", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="gamescore",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="gamescore",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_scores",
                to="users.player",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="games.game",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="games.question",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["status", "-created_at"], name="games_status_a79acb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["room", "-created_at"], name="games_room_id_6e0d1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamescore",
            index=models.Index(
                fields=["game", "-total_score"], name="game_scores_game_id_20ee83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamescore",
            index=models.Index(
                fields=["player", "-total_score"], name="game_scores_player__700039_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gamescore",
            unique_together={("game", "player")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["game", "order"], name="questions_game_id_63c877_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("game", "order")},
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["question", "player"], name="answers_questio_773a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["player", "-created_at"], name="answers_player__c3ea32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["is_correct", "-created_at"], name="answers_is_corr_06ea18_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("question", "player")},
        ),
    ]
