# Generated by Django 5.0.3 on 2025-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
        migrations.AddField(
            model_name="gamescore",
            name="hints_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=200),
        ),
    ]
